#!/usr/bin/env python3
"""Deterministic/network-free A01c correction + host-evidence contract gate."""
from __future__ import annotations
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def fail(msg: str) -> None:
    raise SystemExit("A01c CHECK FAILED: " + msg)

def read(rel: str) -> str:
    p = ROOT / rel
    if not p.is_file():
        fail("missing " + rel)
    return p.read_text(encoding="utf-8")

cargo = tomllib.loads(read("src-tauri/Cargo.toml"))
if cargo.get("package", {}).get("rust-version") != "1.90":
    fail("Cargo package rust-version must match Tauri 2.11.5 upstream MSRV 1.90")
if cargo.get("dependencies", {}).get("tauri", {}).get("version") != "=2.11.5":
    fail("Tauri pin drifted")
if cargo.get("build-dependencies", {}).get("tauri-build", {}).get("version") != "=2.6.3":
    fail("tauri-build pin drifted")

probe = read("tools/a01c_host_runtime_probe.py")
required = [
    "normal-use launch evidence must be collected as a non-root user",
    "XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_CACHE_HOME", "XDG_STATE_HOME", "XDG_RUNTIME_DIR",
    "/proc/net/tcp", "TCP_LISTEN", "socket:", "libpq", "libnode",
    "A01C_SECRET_CANARY_", "navigation_runtime_probe",
    "WAYLAND_DISPLAY", "DISPLAY", "systemctl_command_present", "dbus_session_bus_present",
]
for token in required:
    if token not in probe:
        fail("host probe missing contract token: " + token)
for forbidden in ("sudo ", "pacman -S", "yay ", "paru ", "systemctl --user", "curl ", "wget ", "docker run", "npm install"):
    if forbidden.lower() in probe.lower():
        fail("host probe must not bootstrap/mutate host: " + forbidden)

corrections = read("docs/architecture/08-implementation-corrections-and-debt.md")
if "DEBT-A01-002" not in corrections or "Rust 1.90" not in corrections:
    fail("MSRV correction is not recorded explicitly")
evidence = read("docs/evidence/A01C_HOST_EVIDENCE.md")
for token in ("FACT", "INFERENCE", "PROPOSAL", "UNRESOLVED EXPERIMENT", "tools/uts_verify.py", "Rust 1.90"):
    if token not in evidence:
        fail("A01c evidence missing classification/next-stage marker: " + token)
status = read("docs/IMPLEMENTATION_STATUS.md")
if "A01a+A01b+A01c" not in status or "partially implemented" not in status:
    fail("implementation ledger must retain honest A01c partial status")
# Historical A01c regression evidence must survive later stages without freezing NEXT_PATCH_SEQUENCE.
if "| A03 Rust application/domain boundary" not in status or "tools/uts_verify.py" not in evidence:
    fail("post-A02 SSOT must retain A03 history and delegated host verification")

# A01c must not fabricate generated evidence it could not execute.
if (ROOT / "src-tauri/Cargo.lock").exists():
    lock = read("src-tauri/Cargo.lock")
    if "# This file is automatically @generated by Cargo." not in lock:
        fail("Cargo.lock does not look Cargo-generated")

print("A01c deterministic correction/host-evidence contract: OK")
