#!/usr/bin/env python3
"""Deterministic, network-free A01b acceptance-harness contract gate."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

def fail(msg):
    raise SystemExit("A01b CHECK FAILED: " + msg)

def read(rel):
    p = ROOT / rel
    if not p.is_file(): fail("missing " + rel)
    return p.read_text(encoding="utf-8")

host = read("tools/a01b_host_acceptance.py")
required = [
    '"offline-build"', 'src-tauri/Cargo.lock', 'npm", "ci", "--offline"',
    'cargo", "test"', 'cargo", "build"', '"--locked", "--offline"',
    '"CARGO_NET_OFFLINE": "true"', 'webkit2gtk-4.1', 'gtk+-3.0', 'glib-2.0',
    'dist" / "index.html', 'p2pkanban-arch-native',
]
for token in required:
    if token not in host: fail("host harness missing strict acceptance token: " + token)
for forbidden in ("sudo ", "systemctl", "docker", "postgres", "curl ", "wget ", "npm install"):
    if forbidden.lower() in host.lower(): fail("host harness contains forbidden assumption/network bootstrap: " + forbidden)
if "acceptance unavailable: missing commands:" not in host or "acceptance unavailable: missing pkg-config modules:" not in host:
    fail("host acceptance must fail closed on missing prerequisites")

evidence = read("docs/evidence/A01B_BUILD_ACCEPTANCE.md")
for token in ("partially implemented", "A01c", "FACT", "UNRESOLVED EXPERIMENT", "no `cargo`/`rustc`"):
    if token not in evidence: fail("A01b evidence missing honest-status marker: " + token)
status = read("docs/IMPLEMENTATION_STATUS.md")
if "A01b" not in status:
    fail("implementation ledger lost A01b traceability")
if "**partially implemented" not in status and "**implemented**" not in status:
    fail("implementation ledger must state an explicit A01 status")

debt = read("docs/architecture/08-implementation-corrections-and-debt.md")
if "DEBT-A01-001" not in debt:
    fail("build-evidence environment limitation must be explicit debt/evidence, not hidden")

# Do not accept an invented lock as part of this harness-only patch.
lock = ROOT / "src-tauri" / "Cargo.lock"
if lock.exists():
    text = lock.read_text(encoding="utf-8", errors="replace")
    version_match = re.search(r"(?m)^version = (\d+)$", text)
    version = int(version_match.group(1)) if version_match else None
    if "# This file is automatically @generated by Cargo." not in text or version not in {3, 4}:
        fail(f"Cargo.lock exists but does not look resolver-generated/supported (lock version={version!r})")

print("A01b deterministic acceptance-harness contract: OK")
